# Generated by Django 4.1.5 on 2023-01-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='image',
            new_name='img',
        ),
    ]
